// Code generated by "stringer -type=key"; DO NOT EDIT.

package object

import "strconv"

const (
	_key_name_0 = "MemberOfCultMemberOfAntiCultLawAbidingMissingLimbMissingEyeHeartProblemsSchizophreniaParanoiaAgoraphobiaDepressionPlague"
	_key_name_1 = "lastBoolBoundary"
	_key_name_2 = "STR"
	_key_name_3 = "CHA"
	_key_name_4 = "WIS"
	_key_name_5 = "INT"
	_key_name_6 = "WIL"
	_key_name_7 = "SAN"
	_key_name_8 = "lastNibbleBoundary"
	_key_name_9 = "STRESS"
)

var (
	_key_index_0 = [...]uint8{0, 12, 28, 38, 49, 59, 72, 85, 93, 104, 114, 120}
)

func (i key) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _key_name_0[_key_index_0[i]:_key_index_0[i+1]]
	case i == 16:
		return _key_name_1
	case i == 20:
		return _key_name_2
	case i == 24:
		return _key_name_3
	case i == 28:
		return _key_name_4
	case i == 32:
		return _key_name_5
	case i == 36:
		return _key_name_6
	case i == 40:
		return _key_name_7
	case i == 48:
		return _key_name_8
	case i == 56:
		return _key_name_9
	default:
		return "key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
